// Auto-scroll placeholder keywords shown in SearchBar, keyed by the exact
// category name as stored in products.category (see lib/categories.ts).
// A category with no entry here falls back to GENERIC_SEARCH_KEYWORDS.
export const CATEGORY_SEARCH_KEYWORDS: Record<string, string[]> = {
  "Elektronik": [
    "powerbank",
    "earphone bluetooth",
    "smartwatch",
    "kabel data type c",
    "speaker bluetooth",
    "charger fast charging",
    "lampu led",
  ],
  "Fashion Muslim": [
    "gamis syari",
    "hijab pashmina",
    "mukena travel",
    "baju koko",
    "kerudung instan",
    "gamis kondangan",
    "hijab segi empat",
  ],
  "Fotografi": [
    "tripod hp",
    "ring light",
    "lensa clip hp",
    "gimbal stabilizer",
    "kamera mirrorless",
    "memory card",
    "tas kamera",
  ],
  "Handphone & Aksesoris": [
    "case hp anti gores",
    "tempered glass",
    "kabel data",
    "holder hp",
    "powerbank mini",
    "earphone tws",
    "pop socket",
  ],
  "Hobi & Koleksi": [
    "action figure",
    "gunpla",
    "puzzle",
    "kartu koleksi",
    "diecast mobil",
    "lego",
    "mainan rc",
  ],
  "Ibu & Bayi": [
    "popok bayi",
    "baby carrier",
    "botol susu",
    "stroller bayi",
    "baju bayi",
    "mainan edukasi bayi",
    "minyak telon",
  ],
  "Kesehatan": [
    "masker medis",
    "vitamin c",
    "termometer digital",
    "hand sanitizer",
    "obat herbal",
    "tensimeter",
    "suplemen imun",
  ],
  "Komputer & Aksesoris": [
    "mouse wireless",
    "keyboard mechanical",
    "ssd eksternal",
    "laptop stand",
    "webcam",
    "flashdisk",
    "headset gaming",
  ],
  "Makanan & Minuman": [
    "kopi sachet",
    "snack kekinian",
    "teh celup",
    "madu murni",
    "bumbu masak instan",
    "cemilan pedas",
    "susu bubuk",
  ],
  "Olahraga & Outdoor": [
    "matras yoga",
    "sepatu lari",
    "tas gunung",
    "botol minum olahraga",
    "resistance band",
    "tenda camping",
    "jersey olahraga",
  ],
  "Otomotif": [
    "aksesoris motor",
    "kamera dashboard",
    "helm full face",
    "sarung jok mobil",
    "oli mesin",
    "lampu led motor",
    "cover motor",
  ],
  "Pakaian Pria": [
    "kemeja pria",
    "kaos polos pria",
    "celana chino",
    "jaket pria",
    "kemeja flanel",
    "celana jeans pria",
    "hoodie pria",
  ],
  "Pakaian Wanita": [
    "dress wanita",
    "blouse wanita",
    "atasan wanita",
    "rok plisket",
    "kemeja wanita",
    "crop top",
    "outer wanita",
  ],
  "Perawatan & Kecantikan": [
    "pelembab wajah",
    "serum pencerah",
    "skin cleanser",
    "sunscreen",
    "toner wajah",
    "masker wajah",
    "lip cream",
  ],
  "Perlengkapan Rumah": [
    "panci stainless steel",
    "kompor gas",
    "tumbler",
    "rak dapur",
    "wadah makan",
    "gantungan baju",
    "pisau dapur set",
  ],
  "Sepatu Pria": [
    "sepatu sneakers pria",
    "sepatu formal pria",
    "sandal pria",
    "sepatu olahraga pria",
    "sepatu boots pria",
    "sepatu slip on pria",
    "sepatu kasual pria",
  ],
  "Tas Pria": [
    "tas selempang pria",
    "tas ransel pria",
    "tas kerja pria",
    "dompet pria",
    "tas pinggang pria",
    "tas laptop pria",
    "sling bag pria",
  ],
  "Tas Wanita": [
    "tas selempang wanita",
    "tas ransel wanita",
    "tas tote wanita",
    "dompet wanita",
    "tas pesta",
    "tas kerja wanita",
    "clutch wanita",
  ],
};

// Used on the unfiltered homepage and for any category not in the map above.
export const GENERIC_SEARCH_KEYWORDS: string[] = [
  "skincare",
  "fashion wanita",
  "elektronik & gadget",
  "perlengkapan rumah tangga",
  "aksesoris HP",
  "smartwatch",
  "springbed",
  "meja gaming",
  "kursi gaming",
  "powerbank",
];

export function getSearchKeywords(category?: string): string[] {
  if (category && CATEGORY_SEARCH_KEYWORDS[category]) {
    return CATEGORY_SEARCH_KEYWORDS[category];
  }
  return GENERIC_SEARCH_KEYWORDS;
}
